.Dd $Mdocdate: March 20 2019 $
.Dt PCMPRINT 1
.Os
.Sh NAME
.Nm pcmprint
.Nd prints PCM data into stdout
.Sh SYNOPSIS
.Nm pcmprint
.Op Fl b Ar blocksize
.Op Fl w Ar width
.Op Ar file
.Sh DESCRIPTION
.Nm
reads input (either stdin or file, if specified) and prints to stdout lines visualising the signal.
Input data is assumed to be RAW PCM, signed, 16-bit, little-endian, stereo, with sampling rate of 44100 Hz.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b Ar blocksize
specifies size of the block to operate on.
Size of the block is assumed to be in sampling frames, 4 bytes per frame.
